# headers and icon 
title: Jianxin Yang
info: 杨建新
icon-pic: assets/img/icons-flamingo.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
